[package]
name = "fhe_ops"
version = "0.1.0"
edition = "2021"
description = "FHE operations library"
license = "MIT"

[dependencies]
algebra = { path = "../algebra" }
algebra_derive = { path = "../algebra_derive" }
serde = { workspace = true }
rand = { workspace = true }
num-traits = { workspace = true }


[dev-dependencies]
criterion = { workspace = true }

[features]
default = []
