[package]
name = "piop"
version = "0.1.0"
edition = "2021"
description = "PIOP library"
license = "MIT"

[dependencies]
algebra = { path = "../algebra" }
algebra_derive ={ path = "../algebra_derive" }
fhe_ops ={ path = "../fhe_ops"}
serde = { workspace = true }
rand = {workspace = true }
num-traits = { workspace = true }
itertools ={ workspace = true }

[dev-dependencies]
criterion = "0.5"

[features]
default = []



