[package]
name = "piop"
version = "0.1.0"
edition = "2024"

[dependencies]
algebra = { path = "../algebra" }
pcs = { path = "../pcs" }
fhe_core = { path = "../fhe_core" }
sumcheck = { path = "../sumcheck" }
helper = { path = "../helper" }
trace = { path = "../trace" }

thiserror = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
rand_chacha = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
itertools = { workspace = true }
bincode = { workspace = true }
rayon = { workspace = true }
arc-swap = { workspace = true }

[target.'cfg(all(unix, any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64", target_env = "gnu"))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(all(target_os = "windows", target_env = "msvc"))'.dependencies]
sha2 = { version = "0.10" }

[dev-dependencies]
criterion = { workspace = true }

[features]
default = ["extension_field"]
extension_field = []
