mod evaluate;
mod parameters;

pub use evaluate::Evaluator;
pub use parameters::{
    BABYBEAR_BINARY_128_BITS_PARAMETERS, BABYBEAR_CODE_SPEC, CUSTOM_TERNARY_128_BITS_PARAMETERS,
    DEFAULT_TERNARY_128_BITS_PARAMETERS, GOLDILOCK_CODE_SPEC,
    GOLDILOCKS_BINARY_128_BITS_PARAMETERS,
};
